production:
  adapter: mysql2
  database: travelog_production
  host: localhost
  username: root
  password: root

test:
  adapter: mysql2
  database: travelog_test
  host: localhost
  username: root
  password: root

development:
  adapter: mysql2
  database: travelog_development
  host: localhost
  username: root
  password: root
