development: &sandbox # change to your own
  username: payment_api1.day.com.my
  password: VKWREQHS7UKFNQA2
  signature: ArcneWr3fZIaCcVaXLRmmZnzNkEtAX1Wu1EkZJPoEHJ23XVDJCmCMkQ7
  sandbox: false

test:
  <<: *sandbox

production: &production
  username: SET_YOUR_OWN
  password: SET_YOUR_OWN
  signature: SET_YOUR_OWN
  sandbox: false